-- MySQL Script generated by MySQL Workbench
-- 02/07/15 20:05:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema steamrankings_test_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `steamrankings_test_db` ;

-- -----------------------------------------------------
-- Schema steamrankings_test_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `steamrankings_test_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `steamrankings_test_db` ;

-- -----------------------------------------------------
-- Table `steamrankings_test_db`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamrankings_test_db`.`profiles` ;

CREATE TABLE IF NOT EXISTS `steamrankings_test_db`.`profiles` (
  `id` INT UNSIGNED NOT NULL,
  `community_id` LONGTEXT NOT NULL,
  `persona_name` LONGTEXT NULL,
  `real_name` LONGTEXT NULL,
  `location_country` LONGTEXT NULL,
  `location_province` LONGTEXT NULL,
  `location_city` LONGTEXT NULL,
  `avatar_full_url` LONGTEXT NULL,
  `avatar_medium_url` LONGTEXT NULL,
  `avatar_icon_url` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steamrankings_test_db`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamrankings_test_db`.`games` ;

CREATE TABLE IF NOT EXISTS `steamrankings_test_db`.`games` (
  `id` INT UNSIGNED NOT NULL,
  `name` LONGTEXT NOT NULL,
  `icon_url` LONGTEXT NULL,
  `logo_url` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steamrankings_test_db`.`achievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamrankings_test_db`.`achievements` ;

CREATE TABLE IF NOT EXISTS `steamrankings_test_db`.`achievements` (
  `id` INT NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  `name` LONGTEXT NULL,
  `description` LONGTEXT NULL,
  `unlocked_icon_url` LONGTEXT NULL,
  `locked_icon_url` LONGTEXT NULL,
  PRIMARY KEY (`id`, `game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steamrankings_test_db`.`profiles_has_games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamrankings_test_db`.`profiles_has_games` ;

CREATE TABLE IF NOT EXISTS `steamrankings_test_db`.`profiles_has_games` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` INT UNSIGNED NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  `total_play_time` INT ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `profile_id`, `game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steamrankings_test_db`.`profiles_achievements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamrankings_test_db`.`profiles_achievements` ;

CREATE TABLE IF NOT EXISTS `steamrankings_test_db`.`profiles_achievements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `profile_id` INT UNSIGNED NOT NULL,
  `achievement_id` INT NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  `unlocked_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `profile_id`, `achievement_id`, `game_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
